services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.7
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Map container port 5432 to host port 5433

  redis:
    image: redis:7.2.5
    ports:
      - "6380:6379" # Map container port 6379 to host port 6380
